// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPortfolio.Shared;

namespace MyPortfolio.Shared.Migrations
{
    [DbContext(typeof(MyPortfolioDbContext))]
    [Migration("20210323081217_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyPortfolio.Shared.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("MyPortfolio.Shared.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(513)
                        .HasColumnType("nvarchar(513)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b9262c4-bde3-46b7-904c-8e2d6b773bcf"),
                            About = "I am a software developer, studying Computer Engineering at Selçuk University in Turkey and I'm so motivated to continue with improving my skills in computer science.",
                            AvatarPath = "avatar.png",
                            CVPath = "MyCV.pdf",
                            Description = "I have experience developing Android apps because I produced many apps which I have published on Google Play Store. I am now starting to develop myself in the field of web applications and my goal is to become a full stack developer.",
                            FullName = "Ahmet Bakırcı",
                            Profile = ".NET Full Stack Web Developer"
                        });
                });

            modelBuilder.Entity("MyPortfolio.Shared.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b5a15c2-2a6b-469d-85e8-ee9e2e4ace84"),
                            Description = "A video status application that contains many videos and beautiful statuses that are constantly updated and also allows users to download videos and share them on social networking sites.",
                            ImagePath = "videostatuses.png",
                            Link = "https://play.google.com/store/apps/details?id=com.mahwous.videostatuses",
                            Name = "Video Statuses"
                        },
                        new
                        {
                            Id = new Guid("bbb91f7a-fddb-40de-b83a-6cf5d5833a93"),
                            Description = "A video status application that contains many videos and beautiful statuses that are constantly updated and also allows users to download videos and share them on social networking sites.",
                            ImagePath = "mystatuses.png",
                            Link = "https://play.google.com/store/apps/details?id=com.mahwous.mystatuses",
                            Name = "My Statuses"
                        },
                        new
                        {
                            Id = new Guid("6ef86f66-67c2-4fa1-be48-e3da8b7dbcf0"),
                            Description = "The website of Asia company for the sale and rental of stadiums in Turkey.",
                            ImagePath = "asiacompany.png",
                            Link = "https://jx0hwxn75fznewe0qppjwq-on.drv.tw/AsiaSport/",
                            Name = "Asia For Stadiums"
                        });
                });

            modelBuilder.Entity("MyPortfolio.Shared.Entities.Owner", b =>
                {
                    b.HasOne("MyPortfolio.Shared.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
